project_name: kube-bouncer

builds:
- binary: kubebouncer
  env: [CGO_ENABLED=0]
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64

dockers:
- image_templates: ["ghcr.io/kavinraja-g/{{ .ProjectName }}:{{ .Version }}-amd64"]
  use: buildx
  dockerfile: Dockerfile
  build_flag_templates:
  - --platform=linux/amd64
  - "--label=org.opencontainers.image.created={{ .Date }}"
  - "--label=org.opencontainers.image.title={{ .ProjectName }}"
  - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
  - "--label=org.opencontainers.image.version={{ .Version }}"
- image_templates: ["ghcr.io/kavinraja-g/{{ .ProjectName }}:{{ .Version }}-arm64v8"]
  use: buildx
  dockerfile: Dockerfile
  goarch: arm64
  build_flag_templates:
  - --platform=linux/arm64/v8
  - "--label=org.opencontainers.image.created={{ .Date }}"
  - "--label=org.opencontainers.image.title={{ .ProjectName }}"
  - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
  - "--label=org.opencontainers.image.version={{ .Version }}"

docker_manifests:
- name_template: ghcr.io/kavinraja-g/{{ .ProjectName }}:{{ .Version }}
  image_templates:
  - ghcr.io/kavinraja-g/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/kavinraja-g/{{ .ProjectName }}:{{ .Version }}-arm64v8
- name_template: ghcr.io/kavinraja-g/{{ .ProjectName }}:latest
  image_templates:
  - ghcr.io/kavinraja-g/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/kavinraja-g/{{ .ProjectName }}:{{ .Version }}-arm64v8
