---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsbouncer-server
  namespace: nsbouncer-poc
  labels:
    app: nsbouncer-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nsbouncer-server
  template:
    metadata:
      labels:
        app: nsbouncer-server
    spec:
      containers:
      - name: nsbouncer
        imagePullPolicy: Always
        image: kavinrajaganesan/nsbouncer:latest
        env:
        - name: DENY_NAMESPACES
          value: "prod"
        ports:
        - containerPort: 8443
          name: nsbouncer-api
        volumeMounts:
        - name: nsbouncer-tls-certs
          mountPath: /etc/nsbouncer/certs
          readOnly: true

      volumes:
      - name: nsbouncer-tls-certs
        secret:
          secretName: nsbouncer-tls-secret