# Default values for kubebouncer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/kavinraja-g/kubebouncer
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.1.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources: {}

# Pod placements
nodeSelector: {}
tolerations: []
affinity: {}

# Configure service to be used for webhooks
service:
  type: ClusterIP
  port: 8443

# Secret with TLS certificates used for webhooks
tlsSecret: "kubebouncer-tls-secret" 

# Environment vars used in the webhook server deployment
envVars:
- name: DENY_NAMESPACES # This envVar is required for the NamespaceBouncer
  value: ""
