apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubebouncer.fullname" . }}
  labels:
    {{- include "kubebouncer.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https-api
  selector:
    {{- include "kubebouncer.selectorLabels" . | nindent 4 }}
